version: '3.8'

services:
  app:
    build: .
    container_name: analytics-app  # Memberi nama pada container aplikasi
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PORT=3000
      - REDIS_HOST=10.8.0.3
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    command: npm start